[versions]
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.2.0"
junit = "4.13.2"
androidxJunit = "1.2.1"
espresso = "3.6.1"
firebaseBom = "33.3.0"
googleServices = "4.4.2"
androidGradle = "8.5.2"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }

# Tests
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradle" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
